name: Actualizar Estadísticas en README de Workflows

on:
  schedule:
    - cron: "0 0 * * *"  # Se ejecuta una vez al día
  workflow_dispatch:  # Permite ejecutarlo manualmente

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Obtener estadísticas
        run: |
          echo "## 📊 Estadísticas del Repositorio" > .github/workflows/README.md
          echo "" >> .github/workflows/README.md
          echo "| Métrica         | Valor |" >> .github/workflows/README.md
          echo "|----------------|-------|" >> .github/workflows/README.md
          echo "| 📌 Commits     | $(git rev-list --count HEAD) |" >> .github/workflows/README.md
          echo "| 🐞 Issues      | $(gh issue list --repo ${{ github.repository }} --state all --json number | jq '. | length') |" >> .github/workflows/README.md
          echo "| 🔀 Pull Requests | $(gh pr list --repo ${{ github.repository }} --state all --json number | jq '. | length') |" >> .github/workflows/README.md
          echo "| 👥 Contribuyentes | $(gh repo view ${{ github.repository }} --json contributors --jq '.contributors | length') |" >> .github/workflows/README.md

      - name: Hacer commit y push de los cambios
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .github/workflows/README.md
          git commit -m "Actualizar estadísticas en README de workflows"
          git push

